### PR TITLE
TOOLS-156 add force flag for ize set command

### PR DESCRIPTION
**Pull request by psihachina**
## Changelog: 
- add force flag for ize secret set command

## Test: 
[asciicast](https://asciinema.org/a/VvHLrFZL9BawcHZixLa6YFzzh)

### CODE REVIEW

**Review by AutomationD — CHANGES_REQUESTED** [review]
Looks good, but I'm not sure if the command help is correct to show here.
The user didn't miss a command really. Can this be changed, so we only show 
```
"secret already exists, you can use --force to overwrite it"
```
but no command help?

**Comment by psihachina** [comment]
@AutomationD My bad. This change with the enabled silent usage was committed by accident in the last PR.

**Comment by AutomationD** [comment]
> @AutomationD My bad. This change with the enabled silent usage was committed by accident in the last PR. I fix it

No problem. Could you please re-upload asciinema?

**Comment by psihachina** [comment]
@AutomationD I re-upload asciinema

**Review by AutomationD — APPROVED** [review]
Thank you very much, looks good!

**Pull request merged**
