### PR TITLE
IZE-682 added explain mode for `ize tunnel` commands

### PR DESCRIPTION
**Pull request by psihachina**
## Change:
added explain mode for `ize tunnel` commands

## Test:
[asciicast](https://asciinema.org/a/HQxghA8BuIuunhxbQcKxo1keI)

### CODE REVIEW

**Review by AutomationD — CHANGES_REQUESTED** [review]
Please add an asciinema where explain commands are executed.

**Comment by psihachina** [comment]
@AutomationD My test demonstrates the execution of explain commands. Is not it so?

**Comment by AutomationD** [comment]
I apologize, this is my bad. I didn't realize you are running the whole output.

**Review by igorkotof — APPROVED** [review]

**Review by AutomationD — APPROVED** [review]
Thank you

**Pull request merged**
