### PR TITLE
IZE-354 IZE-249 refactor downloading terraform

### PR DESCRIPTION
**Pull request by psihachina**
## Changelog:
- refactor downloading terraform

## Test:
[asciicast](https://asciinema.org/a/EXrKFf9pXitvJBj3py4MQk4fK)

### CODE REVIEW

**Comment by AutomationD** [comment]
@psihachina Does this solve the download issue of terraform 1.1.9?

**Comment by psihachina** [comment]
@AutomationD 
[asciicast](https://asciinema.org/a/zyPNsHw6Jh9OuaWQyZ1DgmmBg)

**Review by kobrikx — APPROVED** [review]
Thank you for the changes, tests looks good!

**Review by AutomationD — CHANGES_REQUESTED** [review]
Small typo/grammar bits, one question, but otherwise looks good

**Review by AutomationD — APPROVED** [review]

**Pull request merged**
